# Site settings
title: "PySideExtn/PyQtExtn Documentation"
logo: "/favicon.ico"
email: "spinncompany@gmail.com"
description: "Documentation for PySideExtn/PyQtExtn by Khamisi Kibet"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "https://github.com/KhamisiKibet"

# Build settings
remote_theme: "pmarsceill/just-the-docs"
plugins:
  - jekyll-feed

# Auxiliary links
aux_links:
  "PySideExtn/PyQtExtn in Github":
    - "https://github.com/KhamisiKibet/PySideExtn"
  "YouTube":
    - "https://youtube.com/spinntv"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2024"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Theme settings
just_the_docs:
  # Color scheme for the theme
  color_scheme: "light"

  # Specify the default order of the navigation links
  default_order:
    - "Home"
    - "Documentation"
    - "About"
  
  # Site logo
  logo:
    - path: "/assets/logo.png"
      alt: "Logo"
  
  # Search settings
  search_enabled: true
  search:
    search_placeholder: "Search..."
    show_shortcut: true
    shortcut: "/"

  # Navigation links
  nav:
    - title: "Home"
      url: "/"
    - title: "GitHub"
      url: "https://github.com/KhamisiKibet/PySideExtn"
    - title: "YouTube"
      url: "https://youtube.com/spinntv"

  # Social links
  social_links:
    - title: "Email"
      url: "mailto:spinncompany@gmail.com"
    - title: "GitHub"
      url: "https://github.com/KhamisiKibet"
    - title: "YouTube"
      url: "https://youtube.com/spinntv"
