# Site settings
title: "PySideExtn/PyQtExtn Documentation"
logo: "/favicon.ico"
email: "spinncompany@gmail.com"
description: "Documentation for PySideExtn/PyQtExtn by Khamisi Kibet"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "https://github.com/KhamisiKibet"

# Build settings
theme: "minimal-mistakes-jekyll"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Navigation links
nav:
  - title: "Home"
    url: "/"
  - title: "GitHub"
    url: "https://github.com/KhamisiKibet/PySideExtn"
  - title: "YouTube"
    url: "https://youtube.com/spinntv"

# Social links
author:
  name: "Khamisi Kibet"
  avatar: "/assets/images/avatar.png"
  links:
    - label: "Email"
      url: "mailto:spinncompany@gmail.com"
    - label: "GitHub"
      url: "https://github.com/KhamisiKibet"
    - label: "YouTube"
      url: "https://youtube.com/spinntv"

# Footer content
footer:
  content: "Copyright &copy; 2024"

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Theme settings
minimal_mistakes_skin: "default"
show_author: true
social_links:
  - name: "GitHub"
    url: "https://github.com/KhamisiKibet"
  - name: "YouTube"
    url: "https://youtube.com/spinntv"
